{{- if .Values.redash.worker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "redash.fullname" . }}-worker
  labels:
    {{- include "redash.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "redash.fullname" . }}-worker
  minReplicas: {{ .Values.redash.worker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.redash.worker.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.redash.worker.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.redash.worker.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.redash.worker.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.redash.worker.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
