apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redash.fullname" . }}-env
  labels:
    {{- include "redash.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Required security keys
  REDASH_SECRET_KEY: {{ .Values.redash.env.REDASH_SECRET_KEY | default (randAlphaNum 32) | quote }}
  REDASH_COOKIE_SECRET: {{ .Values.redash.env.REDASH_COOKIE_SECRET | default (randAlphaNum 32) | quote }}
  
  # Host configuration
  REDASH_HOST: {{ .Values.redash.env.REDASH_HOST | quote }}
    
  # Feature flags
  REDASH_FEATURE_ALLOW_CUSTOM_JS_VISUALIZATIONS: {{ .Values.redash.env.REDASH_FEATURE_ALLOW_CUSTOM_JS_VISUALIZATIONS | default "true" | quote }}
  REDASH_FEATURE_SHOW_QUERY_RESULTS_COUNT: {{ .Values.redash.env.REDASH_FEATURE_SHOW_QUERY_RESULTS_COUNT | default "true" | quote }}
  
  # Security settings
  REDASH_ENFORCE_CSRF: {{ .Values.redash.env.REDASH_ENFORCE_CSRF | default "false" | quote }}
  REDASH_ENFORCE_HTTPS: {{ .Values.redash.env.REDASH_ENFORCE_HTTPS | default "false" | quote }}
  
  # Logging
  PYTHONUNBUFFERED: {{ .Values.redash.env.PYTHONUNBUFFERED | default "0" | quote }}
  REDASH_LOG_LEVEL: {{ .Values.redash.env.REDASH_LOG_LEVEL | default "INFO" | quote }}
  
  {{- if .Values.mail.server }}
  # Mail configuration
  REDASH_MAIL_SERVER: {{ .Values.mail.server | quote }}
  REDASH_MAIL_PORT: {{ .Values.mail.port | quote }}
  REDASH_MAIL_USE_TLS: {{ .Values.mail.useTLS | quote }}
  REDASH_MAIL_USE_SSL: {{ .Values.mail.useSSL | quote }}
  {{- if .Values.mail.username }}
  REDASH_MAIL_USERNAME: {{ .Values.mail.username | quote }}
  {{- end }}
  {{- if .Values.mail.password }}
  REDASH_MAIL_PASSWORD: {{ .Values.mail.password | quote }}
  {{- end }}
  {{- if .Values.mail.defaultSender }}
  REDASH_MAIL_DEFAULT_SENDER: {{ .Values.mail.defaultSender | quote }}
  {{- end }}
  {{- end }}
  
  {{- if .Values.queryRunners.enabled }}
  # Query runners configuration
  REDASH_ENABLED_QUERY_RUNNERS: {{ join "," .Values.queryRunners.enabled | quote }}
  {{- end }}
  {{- if .Values.queryRunners.disabled }}
  REDASH_DISABLED_QUERY_RUNNERS: {{ join "," .Values.queryRunners.disabled | quote }}
  {{- end }}
  {{- if .Values.queryRunners.additional }}
  REDASH_ADDITIONAL_QUERY_RUNNERS: {{ join "," .Values.queryRunners.additional | quote }}
  {{- end }}
  
  {{- if .Values.alertDestinations.enabled }}
  # Alert destinations configuration
  REDASH_ENABLED_DESTINATIONS: {{ join "," .Values.alertDestinations.enabled | quote }}
  {{- end }}
  {{- if .Values.alertDestinations.additional }}
  REDASH_ADDITIONAL_DESTINATIONS: {{ join "," .Values.alertDestinations.additional | quote }}
  {{- end }}
  
  {{- if .Values.sso.enabled }}
  # SSO configuration
  REDASH_SAML_METADATA_URL: {{ .Values.sso.saml.metadataUrl | default "" | quote }}
  REDASH_SAML_ENTITY_ID: {{ .Values.sso.saml.entityId | default "" | quote }}
  REDASH_SAML_CALLBACK_URL: {{ .Values.sso.saml.callbackUrl | default "" | quote }}
  REDASH_SAML_LOGIN_ENABLED: {{ .Values.sso.saml.loginEnabled | default "true" | quote }}
  {{- end }}
