apiVersion: v1
kind: Service
metadata:
  name: {{ include "redash.fullname" . }}-web
  labels:
    {{- include "redash.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.redash.web.service.type }}
  ports:
    - port: {{ .Values.redash.web.service.port }}
      targetPort: {{ .Values.redash.web.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "redash.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
