apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redash.fullname" . }}-sso
  labels:
    {{- include "redash.labels" . | nindent 4 }}
type: Opaque
stringData:
  metadata-url: {{ .Values.sso.saml.metadataUrl | default "" | quote }}
  entity-id: {{ .Values.sso.saml.entityId | default "" | quote }}
  callback-url: {{ .Values.sso.saml.callbackUrl | default "" | quote }}
